kibana-alert-router:
  image:
    imageURL: "nexus.investing.com/gar-europe/investing-com-euro-production/docker-prod-local/finbox.kibana-alert-router"
    pullPolicy: "Always"
    tag: v0.1.2-dev
    command: []
    args: []

  serviceName: kibana-alert-router

  resources:
    limits:
      cpu: "400m"
      memory: "300Mi"
    requests:
      cpu: "200m"
      memory: "150Mi"

  replicaCount: 1

  configMap:
    NODE_ENV: GCP-PROD-AMS
    ROUTER_ID: investing-alerts
    ELASTICSEARCH_URL: http://elasticsearch-es-http.elastic-system.svc.cluster.local:9200
    ELASTICSEARCH_ALERT_INDEX: kibana-alert-history-default

  vaultMap:
    kv/data/applications/elastic-system/kibana-alert-router:
      - OPSGENIE_API_KEY
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
